version: "3.8"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
